---
title: "Circular Economy Experiments of the SFC Model - JBF Code"
author: "Oriol Vallès Codina"
date: "`r Sys.Date()`"
output:
  # word_document: default
  # keep_tex: true

  # pdf_document:
  #   toc: true
  #   toc_depth: 3
  #   number_sections: true
  html_document:
    toc: TRUE
    toc_float: TRUE
format:
  html:
    self-contained:
      true
---

# Initialization 

```{r setup, warning = FALSE, message = FALSE, exclude = TRUE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 9, fig.height = 10)

library(reshape2)
library(dplyr)
library(ggplot2)
library(printr)
library(kableExtra)
library(flextable)
library(tools)

sectors <- c('Manufacturing', 'Agriculture', 'Services', 'Waste', 'Recycling')
countries <- c('EU', 'RoW')
directory <- ""
variable.table <- read.csv(paste0(directory, 'data/Variable_Definitions.csv'))
scenario.table <- read.csv(paste0(directory, 'data/Scenario_List.csv'), row.names = 1)

#### LOAD FUNCTIONS ####
source(paste0(directory, 'functions/1_Model_rev (JBF_Revised Feb_with public Investment)_adapted.R')) # model
source(paste0(directory, 'functions/auxiliary.R')) # load.init, load.target, return.instr.val
source(paste0(directory, 'functions/plot_variable_function_Feb27.R')) # plotting functions 
source(paste0(directory, 'functions/5A_Tables_Function_May20.R')) # table functions (BS and TFM)

#### LOAD TARGET VALUES IN WIDE AND LONG FORMAT ####
tmp <- load.target(paste0(directory, 'data/target_values.xlsx'))
target.set <- tmp$long
target.table.0 <- tmp$wide

target.variables <- colnames(target.table.0)
target.indices <- colnames(target.table.0) %in% target.variables
target.table <- target.table.0[ , target.indices]
```

# Results

```{r scenario.plots, eval = FALSE}
# SCENARIOS PLOTS
# Pre-saved list
# It just saves them into a list, it does not print them as pdf

scenario.plots <- list()
for (i in 1 : nrow(scenario.table))
{
  # pdf(paste0(directory, 'figures/shock_', i, '_3_NEWRUN.pdf'), width = 10, height = 6)
  
  scenario.plots[[i]] <- list(shock.title = shock.title <- paste0('Shock ', i, ': ', scenario.table$Shock[i]))  
  
  df <- shock.long(baseline, i)
  df$area <- as.factor(df$area)
  levels(df$area) <- countries

  # Selected Vars
  scenario.plots[[i]]$selected.vars <- filter(df, variable %in% selected.vars & sector == 'aggregate') %>% 
    ggplot(aes(x = time, y = value, color = area, linetype = scenario)) + facet_wrap(~ name, scales = 'free') + geom_line() + 
    geom_vline(xintercept = baseline$simulation$parameters['t.shock', ], linetype = 'dashed', linewidth = .4) +
    labs(title = shock.title, subtitle = 'Selected Aggregate Macroeconomic Indicators. Vertical dashed line indicates shock time')
  
 # Labor Market
  category <- 'labor.market'
  scenario.plots[[i]]$labor.market <- df %>% filter(type == category & sector != 'aggregate') %>% 
    ggplot(aes(x = time, y = value, color = sector, linetype = scenario)) + geom_line() + facet_grid(name ~ area, scales = 'free') + 
    theme(strip.text.y.right = element_text(angle = 0)) +
    geom_vline(xintercept = baseline$simulation$parameters['t.shock', ], linetype = 'dashed', linewidth = .4) + 
    labs(title = shock.title, subtitle = 'Industry-level Labour Market Indicators. Vertical dashed line indicates shock time')

 # Ecological
  category <- 'ecological'
  excl.vars <- c('x_mat', 'gamma_A')

  scenario.plots[[i]]$ecological <- filter(df, !variable %in% excl.vars & type == category & sector == 'aggregate') %>% 
    ggplot(aes(x = time, y = value, color = area, linetype = scenario)) +
    facet_wrap( ~ name, scales = 'free') + geom_line() +
    geom_vline(xintercept = baseline$simulation$parameters['t.shock', ], linetype = 'dashed', linewidth = .4) + 
    labs(title = shock.title, subtitle = 'Aggregate Ecological Indicators. Vertical dashed line indicates shock time')
  
  # Print Plots
  # print(scenario.plots[[i]]$selected.vars)
  # print(scenario.plots[[i]]$labor.market)
  # print(scenario.plots[[i]]$ecological)
  
  # dev.off()
}
```

## Specific Shock

```{r specific.shock.run}
# Load Initial State
recycling.init <- load.init(paste0(directory, 'data/initial_values_mar21_jbf.xlsx'))

# Run Baseline
recycling.init$parameters['shock', ] <- 0
baseline.run <- run.model(recycling.init)

# Run Shock
recycling.init$parameters['shock', ] <- 4
recycling.run <- run.model(recycling.init)

# Higher Recycling Rate
i <- 4
shock.title <- paste0('Shock ', i, ': ', scenario.table$Shock[i])
  
df <- shock.long(baseline.run, recycling.run)
df$area <- as.factor(df$area)
levels(df$area) <- countries

# Selected Vars
p.selected.vars <- filter(df, variable %in% selected.vars & sector == 'aggregate') %>% 
  ggplot(aes(x = time, y = value, color = area, linetype = scenario)) + facet_wrap(~ name, scales = 'free') + geom_line() + 
  geom_vline(xintercept = baseline$simulation$parameters['t.shock', ], linetype = 'dashed', linewidth = .4) +
  labs(title = shock.title, subtitle = 'Selected Aggregate Macroeconomic Indicators. Vertical dashed line indicates shock time') + 
  xlim(50, 100)

# Labor Market
category <- 'labor.market'
p.labor.market <- df %>% filter(type == category & sector != 'aggregate') %>% 
  ggplot(aes(x = time, y = value, color = sector, linetype = scenario)) + geom_line() + facet_grid(name ~ area, scales = 'free') + 
  theme(strip.text.y.right = element_text(angle = 0)) +
  geom_vline(xintercept = baseline$simulation$parameters['t.shock', ], linetype = 'dashed', linewidth = .4) + 
  labs(title = shock.title, subtitle = 'Industry-level Labour Market Indicators. Vertical dashed line indicates shock time') + 
  xlim(50, 100)

# Ecological
category <- 'ecological'
excl.vars <- c('x_mat', 'gamma_A')
p.ecological <- filter(df, !variable %in% excl.vars & type == category & sector == 'aggregate') %>% 
  ggplot(aes(x = time, y = value, color = area, linetype = scenario)) +
  facet_wrap( ~ name, scales = 'free') + geom_line() +
  geom_vline(xintercept = baseline$simulation$parameters['t.shock', ], linetype = 'dashed', linewidth = .4) + 
  labs(title = shock.title, subtitle = 'Aggregate Ecological Indicators. Vertical dashed line indicates shock time') + 
  xlim(50, 100)

# Print Plots
print(p.selected.vars)
print(p.labor.market)
print(p.ecological)

pdf(paste0(directory, 'figures/recycling_shock.pdf'), width = 10, height = 8)
print(p.selected.vars)
print(p.labor.market)
print(p.ecological)
dev.off()
```